# -*- coding: utf-8 -*-
"""BT01_ThapHaNoi.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPWeT-0oPMd0nrSILDkslMLCL_WI5CLB
"""

def thapHaNoi(n, ToaMot, ToaHai, ToaBa):

  if n == 1:
      print("Chuyen tu", ToaMot, "sang", ToaBa)
  else:
      thapHaNoi(n-1, ToaMot, ToaBa, ToaHai)
      print("Chuyen tu", ToaMot, "sang", ToaBa)
      thapHaNoi(n-1, ToaHai, ToaMot, ToaBa)

thapHaNoi(2,'A','B','C')