# -*- coding: utf-8 -*-
"""BT02_USCLN.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153Dp7pQzaytqFrTX26rI4uIUbDuHKrJD
"""

def uscln(a,b):
    if (b == 0):
        return a;
    return uscln(b, a%b);

a = int(input("Nhap so nguyen duong a ="));
b = int(input("Nhap so nguyen duong b ="));
print("Ước số chung lớn nhất của", a, "và", b, "là:",uscln(a,b));