# -*- coding: utf-8 -*-
"""BT03_GiaiThua.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xFaNc1gq-UVz45g8Rmom988--CJ39Gkd
"""

def n_giai_thua(n):
    s = 1;
    if (n == 0 or n == 1):
        return s;
    else:
        for i in range(2,n+1,1):
            s = s * i;
        return s;
 
n = int(input("Nhập số nguyên dương n = "));
print( n,"! = ",n_giai_thua(n));