# -*- coding: utf-8 -*-
"""BT09_HangDoiQueue.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpMg-d5hvn2AQhABP8yAUf56iGZ7LOq0
"""

queue = []
 
# Adding elements to the queue
queue.append('a')
queue.append('b')
queue.append('c')
 
print("Initial queue")
print(queue)
 
# Removing elements from the queue
print("\nElements dequeued from queue")
print(queue.pop(0))
print(queue.pop(0))
print(queue.pop(0))
 
print("\nQueue after removing elements")
print(queue)