# -*- coding: utf-8 -*-
"""BT10_BT11_CayDuyetTruocSau.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GedHlmflP8jFZX5HpvZTFSjUUyVYjFhY
"""

pip install binarytree

from binarytree import build
values = [7, 3, 2, 6, 9, None, 1, 5, 8]
root = build(values)
print(root)
print(root.preorder) # duyệt cây theo thứ tự trước
print(root.postorder) # duyệt cây theo thứ tự sau